### PR TITLE
fixes and adaptions

### PR DESCRIPTION
**Pull request by meisterkaiser**
Hi Dirk,

fixes and small adaptations that should go upstream back to the base repo - as discussed.
Please review ...

Best, tom

### CODE REVIEW

**Review by dwenzel — APPROVED** [review]

**Comment by dwenzel** [comment]
@meisterkaiser 
Thanks a lot, Tom!
I decided to merge your request into the develop branch. Your contributions will be included in the next version.

**Review by IchHabRecht — COMMENTED** [review]
https://github.com/CPS-IT/vcc/pull/1/commits/6ccd167c6f611e3f973760009f42a4f1de7d1cb5

This comment is replaced during page rendering. Removing it from the template may result in missing JS and/or JavaScript functionality.

**Review by IchHabRecht — COMMENTED** [review]
https://github.com/CPS-IT/vcc/pull/1/commits/1bda8425353a12e75ea4febc6d61a8529616324e

Unfortunately this patch is completely broken. First, Esi processing is disabled for POST requests. This means that is not needed to handle POST parameters at all. Secondly, this patch enables the possibility of cache poisoning as for different GET parameters different esi cache entries are generated (even if the result is the same). Adding GET parameters to the generated link should be handled by some configuration properties in TypoScript setup but not be enabled by default!

**Review by IchHabRecht — COMMENTED** [review]
https://github.com/CPS-IT/vcc/pull/1/commits/e72fe611f91da51ec53876f2a0b29b8cf0767a72

A sitemap should not contain any esi / INT objects at all.

**Comment by meisterkaiser** [comment]
> [6ccd167](https://github.com/CPS-IT/vcc/commit/6ccd167c6f611e3f973760009f42a4f1de7d1cb5)
> 
> This comment is replaced during page rendering. Removing it from the template may result in missing JS and/or JavaScript functionality.

Leaving the commented line  breaks rendered output in case of xml (sitemap.xml through cs_seo, rss). Other suggestions to fix this?

**Comment by IchHabRecht** [comment]
> > [6ccd167](https://github.com/CPS-IT/vcc/commit/6ccd167c6f611e3f973760009f42a4f1de7d1cb5)
> > This comment is replaced during page rendering. Removing it from the template may result in missing JS and/or JavaScript functionality.
> 
> Leaving the commented line breaks rendered output in case of xml (sitemap.xml through cs_seo, rss). Other suggestions to fix this?

I just had another look into the TYPO3 code and found out that the comment is part in PageRenderer template but is replaced in DocumentController (and some other backend controller) only. So removing the placeholder should be fine. Still I don't get the issue/use case where you have an INT object on a sitemap rendering.

**Comment by dwenzel** [comment]
Hi @IchHabRecht,
thank you. We discussed the review and agree with you on this points 
* POST params should be disabled
* cache poisoning is a risk and should be avoided

However it might become difficult to handle _all_ legit GET params by configuration. It would not suffice to whitelist parameters by name only but the range of values should be restricted too.

These restrictions seem to be the toughest part in the use case addressed by Toms contributions. 

> comment is part in PageRenderer template but is replaced in DocumentController (and some other backend controller)

Thats right. There was another occurence in `class.tx_t3editor_hooks_fileedit` in TYPO3 4.5. I guess we can ignore this one ;)

>issue/use case where you have an INT object on a sitemap rendering. 

According to Tom they use an extension where the sitemap is rendered on the fly for some reasons but he will dig into it further

I thought of skipping the cache entry completely for certain parameters and/or omit others.

**Comment by IchHabRecht** [comment]
Hi @dwenzel,

GET parameter handling is already included (correctly) but misses one TypoScript configuration. In https://github.com/CPS-IT/vcc/blob/master/Classes/Hooks/ContentPostProcessHook.php#L126 the addQueryString method is validated according to an existing cHash for the current request. The only thing missing is to enable addQueryString with `'addQueryString' => !empty($addQueryStringMethod)`. This should be the valid fix to include existing GET parameters correctly and prevent any cache poisoning.

**Pull request merged**
